### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by NoelMatinez** [juliasilge/tidylo#2]
Hello! 

I can't install the package from the install_github("juliasilge/tidylo") source. I get this error: 

---------------------------------------------------------------------------------------------
Error: HTTP error 401.
  Bad credentials

  Rate limit remaining: 58/60
  Rate limit reset at: 2019-07-08 16:57:49 UTC 
---------------------------------------------------------------------------------------------

So, need I some credentials to install the package? 
Thanks a lot!

**Comment by juliasilge** [comment]
No, you shouldn't need any credentials to install the package. 

Can you install other R packages from GitHub? Do you have [any GitHub PAT](https://usethis.r-lib.org/articles/articles/usethis-setup.html#get-and-store-a-github-personal-access-token) set, but perhaps incorrectly?

**Comment by juliasilge** [comment]
Were you able to get this package installed? Let me know if you're still having troubles!
